spring:
  application:
    name: dubbo-consumer-zk
  cloud:
    zookeeper:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 19001
dubbo:
  registry:
    address: zookeeper://192.168.30.201:3181,192.168.30.201:3182,192.168.30.201:3183
