spring:
  application:
    name: rocketmq-consume-example
  cloud:
    stream:
      bindings:
        input1:
          destination: test-topic
          content-type: text/plain
          group: test-group1
      rocketmq:
        binder:
          name-server: 192.168.30.204:9876
server:
  port: 28088

